### ISSUE TITLE
Possible mistake?

### ISSUE THREAD

**Issue by dtow55** [learn-co-curriculum/ruby-posting-requests#11]
In the lesson, it shows how to pass params in the request body as a JSON object: 

Faraday.post("https://url/to/api") do |req|
  req.body = "{ "my_param": my_value }"
end

Note that there are "" quotes around the object.

In the subsequent lab, 'Working with APIs", my code fails if I include the quotation marks, but works without them: 

DOES NOT PASS:
req.body = "{ 'client_id': #{client_id}, 'client_secret': #{client_secret}, 'code': #{code} }"
PASSES:
req.body = { 'client_id': client_id, 'client_secret': client_secret, 'code': code }

Was not sure what the purpose of the quotation marks was, and maybe worth noting / correcting when they are necessary or not necessary.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
