### ISSUE TITLE
Searches controller includes Foursquare client ID and secret

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/ruby-posting-requests#12]
There is a Foursquare client ID and secret included in `app/controllers/searches_controller.rb`. These should be removed; the lab should instead use credentials stored in the user's `.env` file.

Reported by @eplof44.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe this issue has been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
