### ISSUE TITLE
Problem Adding Tips

### ISSUE THREAD

**Issue by AndrewHongUW** [learn-co-curriculum/ruby-posting-requests#13]
Filled out lab exactly per the instructions. Each time I add a tip to a new coffeeshop (regardless of zipcode typed in), a default tip is being added. #

-

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
