### ISSUE TITLE
bug with "ask question forum"

### ISSUE THREAD

**Issue by Alvinluipo** [learn-co-curriculum/ruby-posting-requests#4]
won't be about to close the forum or minimize it after opening it, the way to minimize it or close it is by refreshing the web page.

**Comment by AnnJohn** [comment]
hi @Alvinluipo thanks for raising this. We use this space for issues specifically related to the curriculum content so can you actually file a bug report for this. If you hover over your profile pic in Learn, you'll get a menu with an option there to file a bug report. Thanks!
